apiVersion: apps/v1
kind: Deployment
metadata:
  name: pix-produtor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pix-produtor
  template:
    metadata:
      labels:
        app: pix-produtor
    spec:
      containers:
        - name: pix-produtor
          image: your-docker-repo/pix-produtor:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: pix-produtor
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: pix-produtor
